# --- 永続化モード（アプリ直下にDBファイルを作成） ---
spring.datasource.url=jdbc:h2:file:./data/aimaitenki-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- JPA設定（テーブル自動生成＋更新） ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- H2コンソール設定 ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

weatherapi.key=